#!/bin/bash
#
# Puts "Update PC20 Wiki.command" on the Desktop: double-click it to pull new
# episodes in and publish them now — the same as `npm run episodes`, without a
# terminal to open first.
#
# A .command rather than an .app, for the reason pc20-clips/tools/make-launcher.sh
# gives: the Desktop is iCloud-synced on this Mac, and an .app bundle there launches
# unreliably once iCloud strips its signature. A plain script has nothing to strip.
# It opens a Terminal window, which here is a feature: you see what was published.
#
#   scripts/make-launcher.sh

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CMD="$HOME/Desktop/Update PC20 Wiki.command"

cat > "$CMD" <<SH
#!/bin/bash
# Pulls this week's Podcasting 2.0 episode into the PC 2.0 Wiki and publishes it.
# Generated by $REPO/scripts/make-launcher.sh — edit that, not this.

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
set -o pipefail   # so a failed update is not hidden by tee succeeding
cd "$REPO" || { echo "pc20-wiki is not at $REPO"; read -n 1 -s; exit 1; }

echo "Updating the PC 2.0 Wiki with new episodes..."
echo

# The publish step steps aside if the 15-minute job is already publishing.
if [ -d /tmp/pc20-wiki-auto-publish.lock ]; then
  busy=1
fi

log=\$(mktemp)
if npm run --silent episodes 2>&1 | tee "\$log"; then
  echo
  if [ -n "\${busy:-}" ]; then
    echo "The wiki was already publishing. Anything new goes out within 15 minutes."
  elif [ ! -s "\$log" ]; then
    echo "Nothing new — the wiki already has every episode."
  else
    echo "Done. The wiki is live in about a minute: https://pc20-wiki.vercel.app/transcripts/"
  fi
else
  echo
  echo "Something failed — the lines above say what."
fi
rm -f "\$log"

echo
echo "Press any key to close this window."
read -n 1 -s
SH

chmod +x "$CMD"
echo "Built: $CMD"
